### ISSUE TITLE
no favicon in tabs ?

### ISSUE THREAD

**Issue by mikakun** [gnome-integration-team/firefox-gnome-css#6]
(they reappear if i disable the style sheet)
apologiez but no idea which rule hides them

**Comment by meshy** [comment]
See https://github.com/gnome-integration-team/firefox-gnome-css/blob/df8086bf404e9398fd4a3cac03dbff60eef6b0a0/theme.css#L475-L478

It's deliberate! (See also #4)

**Comment by meshy** [comment]
Deleting that line out seems to have done the trick for me.

**Comment by mikakun** [comment]
i need to sleep no idea what came through my mind of course there were never favicon in the gnome extension before as well
sorry

**Comment by meshy** [comment]
Perhaps my old installation was dodgy, but I thought I could remember them being there -- perhaps I've just spent too long without the plugin! `:P`

**Comment by meshy** [comment]
No need to be sorry `;)`
